[package]
name = "ch06_meminfo_linux"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.161"
nix = { version = "0.29.0", features = ["uio"] }
# procps = { git = "https://github.com/uutils/procps.git" }
procps = { path = "../../../forks/procps" }
